[tool.poetry]
name = "lang-parse"
version = "0.1.0"
description = ""
authors = ["Iwo Herka <iwo.herka@makimo.pl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
tree-sitter = "^0.20.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
