version: '3.7'

networks:
  namebench:
    external: true

services:
   db:
      image: postgres:latest
      container_name: namebench_db
      environment:
        POSTGRES_DB: namebench
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
      ports:
        - 5432:5432
      networks:
        namebench: {}
